#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 28 01:24:12 2019

@author: Han
"""
import re
# copy positions from excel and translated int0 [[88,88],[168,168],......]

a = "48	55	58	60	70	73	174	204	221	224	266	281	329	433	436	497	501	512	517	525	526	532	533	541	558	561	582	700	754	779	811	819	821	823	839	854"

b = re.sub("\s+", ",", a.strip())

txtlist = b.split(",")

strToIntlist = []

for i in txtlist:
    strToIntlist.append(int(i))

FinalList = []
for i in strToIntlist:
    innerList = []
    innerList.append(i)
    innerList.append(i)
    FinalList.append(innerList)

print(FinalList)
    
